name 'xebialabs-xldeploy'
version '1.2.3'
author 'xebialabs'
license 'Apache V2.0'
project_page 'https://github.com/xebialabs/xebia-deployit.git'
source 'https://github.com/xebialabs/xebia-deployit.git'
summary 'Puppet module for xldeploy'
description 'This module can be used to install and configure a xldeploy infrastructure'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'puppetlabs/inifile', '>= 1.0.0'
dependency 'puppetlabs/concat', '>= 1.0.0'
dependency 'dalen/puppetdbquery', '>= 1.4.0'
dependency 'jtopjian/sshkeys', '0.5.0'
dependency 'puppetlabs/pe_gem', '>= 0.1.0'
