name 'puppet-xldeploy'
version '1.2.5'
author 'xebialabs'
license 'Apache v2.0'
project_page 'https://github.com/xebialabs/puppet-xldeploy.git'
source 'https://github.com/xebialabs/puppet-xldeploy.git'
summary 'Puppet module for XL Deploy'
description 'This module can be used to install and configure a XL Deploy infrastructure'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'puppetlabs/inifile', '>= 1.0.0'
dependency 'puppetlabs/concat', '>= 1.1.0'
dependency 'dalen/puppetdbquery', '>= 1.4.0'
dependency 'jtopjian/sshkeys', '0.5.0'
dependency 'puppetlabs/pe_gem', '>= 0.1.0'
